#tablet specs
TABLET_MAX_X_POS = 12800
TABLET_MAX_Y_POS = 9600
TABLET_OFFSET_X = 0
TABLET_OFFSET_Y = 0

#pc specs
ALL_MONITORS_RES_X = 1920
ALL_MONITORS_RES_Y = 1080

#configuration
MAPPED_MONITOR_RES_X = 1920
MAPPED_MONITOR_RES_Y = 1080
MONITOR_OFFSET_X = 0
MONITOR_OFFSET_Y = 0
PRESSURE_DEADZONE = 0
PRESSURE_OFFSET = 0

#serial port
SERIAL_PORT_PATH = "COM3"