#specs
TABLET_MAX_X_POS = 12800
TABLET_MAX_Y_POS = 9600

ALL_MONITORS_RES_X = 3840
ALL_MONITORS_RES_Y = 1080
MAPPED_MONITOR_RES_X = 1920
MAPPED_MONITOR_RES_Y = 1080
OFFSET_X = 0
OFFSET_Y = 0

#vmulti
VMULTI_DEVICE_VENDOR_ID = 0x00ff
VMULTI_DEVICE_PRODUCT_ID = 0xbacc
VMULTI_ID = 0x40
VMULTI_REPORT_ID_WINDOWSINK = 0x05
VMULTI_REPORT_ID_ABSOLUTE_POINTER = 0x09

OUTPUT_MODE = VMULTI_REPORT_ID_WINDOWSINK #VIRTUAL_MULTITOUCH_REPORT_ID_WINDOWSINK or VIRTUAL_MULTITOUCH_REPORT_ID_ABSOLUTE_POINTER

VMULTI_MONITOR_SCALING_X = (32767 / TABLET_MAX_X_POS) * (MAPPED_MONITOR_RES_X / ALL_MONITORS_RES_X)
VMULTI_MONITOR_SCALING_Y = (32767 / TABLET_MAX_Y_POS) * (MAPPED_MONITOR_RES_Y / ALL_MONITORS_RES_Y)
VMULTI_MONITOR_OFFSET_X = 32767 * (OFFSET_X / ALL_MONITORS_RES_X)
VMULTI_MONITOR_OFFSET_Y = 32767 * (OFFSET_Y / ALL_MONITORS_RES_Y)

#serial port
SERIAL_PORT_PATH = "COM3"
SERIAL_PORT_INITIAL_BAUD_RATE = 9600
SERIAL_PORT_FINAL_BAUD_RATE = 19200
SERIAL_PORT_BYTESIZE = 8
SERIAL_PORT_TIMEOUT = 1
SERIAL_PORT_STOPBITS = 1

#wacom serial port commands
GLOBAL_RESET_TO_WACOM_IV_COMMAND = "#"
KT_0405_R_SETTINGS_COMMAND = "~*F233C900"
KT_0405_R_RESOLUTION_COMMAND = "NR2540"